access_points: ['daos-server-03f8']
transport_config:
  allow_insecure: true
provider: ofi+tcp;ofi_rxm
disable_vfio: true
disable_vmd: true
nr_hugepages: 4096
control_log_file: /tmp/daos_control.log

servers:
-
   targets: 12
   nr_xs_helpers: 0
   first_core: 1
   fabric_iface: eth0
   log_mask: ERR
   log_file: /tmp/daos_server.log

   env_vars:
      - FI_OFI_RXM_DEF_TCP_WAIT_OBJ=pollfd

   scm_mount: /mnt/daos0
   scm_class: ram
   scm_size: 100

   bdev_class: nvme
   bdev_list: ["0000:00:04.0"]
